### ISSUE TITLE
No .dll or .modcomponent files

### ISSUE THREAD

**Issue by JesseWV** [Arkhorse/MapManager#1]
This project seems to be uncompiled and does not contain any .dll and/or .modcomponent files that are needed for installation.

**Comment by Arkhorse** [comment]
Please do not open PEBCAK issues

**Comment by JesseWV** [comment]
Oh sorry I think it's just the link on https://xpazeman.com/tld-mod-list/. The "latest" link isn't working. I'd check your other releases too.

It has:
 https://github.com/Arkhorse/MapManager/releases/latest/download/MapManager.dll 

...but the actual link is:
https://github.com/Arkhorse/MapManager/releases/download/v1.1.0-RC-1/MapManager.dll
