### ISSUE TITLE
Game crashing w/ this mod

### ISSUE THREAD

**Issue by Longdarkgirlie** [Arkhorse/MapManager#4]
The mod was updated and now every time I try to “reveal” the map the game freezes and crashes. After the update it just stopped working.

**Comment by finnjvl** [comment]
Same here, but I there is solution to use mod while waiting bugfix:
Jsst downgrade back to 1.1.3 version at it work just fine....
And it need to remove autoupdate plugin, cause it will update mod back to newer version when game/ML start.

**Comment by Longdarkgirlie** [comment]
Ok thank you

**Comment by Arkhorse** [comment]
Please post a log, found in the MelonLoader folder. However, I think this is due to the update containing test code I thought was excluded.

**Comment by finnjvl** [comment]
Don't have that old logfile cause I downgrade mod , but i upload it couple of days ago  to discrord/botspam to try find out why game crash. I think it like :  03.06.2024 00.29

**Comment by Arkhorse** [comment]
> Don't have that old logfile cause I downgrade mod , but i upload it couple of days ago to discrord/botspam to try find out why game crash. I think it like : 03.06.2024 00.29

You will need to find it yourself, then link it here. Botspam is difficult to find anything. You can use a search keyword to help narrow it down, just use your username and the botspam as the channel (something like `from:yourusername in:bot-spam`

**Comment by Arkhorse** [comment]
Fixed with https://github.com/Arkhorse/MapManager/commit/1ab34a7a76e91a797ac6964cd196a578ccff8f8a. Release coming soon

**Comment by finnjvl** [comment]
> Fixed with [1ab34a7](https://github.com/Arkhorse/MapManager/commit/1ab34a7a76e91a797ac6964cd196a578ccff8f8a). Release coming soon

Tnx :)
